### ISSUE TITLE
Add support for release only on successful build

### ISSUE THREAD

**Issue by cdoconno** [QsonLabs/qcluster#11]
#### Issue

Our actions build runs on the following matrix:

```
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]
```
However, we do not want to release on every matrix. The above is for testing on all operating systems and versions by default before release and will prevent us from pushing a release that does not work.

We want a secondary job for release that configures only 1 operating system and pushes a version to PyPI.
